services:
  core:
    build: 
      context: ./back
      dockerfile: ../docker/images/geometry-core/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./back/:/usr/geometry/back
      # - /usr/geometry/back/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - ./docker/env/back/geometry-core.env
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=pwd
    ports:
      - 5432:5432
    # volumes:
    #   - ./data/postgis:/var/lib/postresql/data
