services:
  geometry:
    container_name: geometry_node
    build:
      context: ${GEOMETRY_ROOT}/
      dockerfile: docker/images/geometry-core/Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ${GEOMETRY_ROOT}/back:/usr/geometry/back
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - ${GEOMETRY_ROOT}/docker/env/back/geometry-core.env
    depends_on:
      - postgis

  postgis:
    container_name: geometry_postgis
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=pwd
    ports:
      - 5432:5432
